name: Auto Unzip
on:
push:
paths:
- '*.zip'
permissions:
contents: write
jobs:
unzip:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
- name: Extract And Push
run: unzip -o "*.zip" && rm "*.zip" && git config user.name "github-actions[bot]" && git config user.email "github-actions[bot]@users.noreply.github.com" && git add . && (git diff --staged --quiet || (git commit -m "Unzipped files" && git push))
