name: Unzip and Commit

on:
  workflow_dispatch:
  push:

permissions:
  contents: write

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Unzip file
        run: |
          unzip -o myfile.zip -d extracted

      - name: Commit extracted files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add extracted/

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Unzip files"
            git push
          fi

      - name: Upload extracted files
        uses: actions/upload-artifact@v4
        with:
          name: extracted-files
          path: extracted/                
